# Generated by Django 3.1.5 on 2021-01-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210125_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_cadastro',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
