# Generated by Django 3.1.5 on 2021-01-26 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210125_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefone',
            field=models.CharField(max_length=13),
        ),
    ]
